# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd98d1e77c0b204d9312c52aab9d7363537e5e136b4eec9e58c45cea35ab56300c4e13ab347e0e10e1fb604bbaf110d95aa7fb95f8863a313baeaf5cb569139

test:
  secret_key_base: 319311e77992096b28160158cba76e87bb6003ea5d2912a0ba5119af69cd65497de778a0cda3bf181410d551717a14f9e47590e71975b7861a5efce1fa5356fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
